variables:
  DOCKER_HOST: "tcp://docker:2375"
services:
  - docker:dind

stages:
  - test

test:
  stage: test
  image: openjdk:17-alpine

  script:
    - chmod +x ./gradlew
    - ./gradlew test
    - cat build/reports/jacoco/test/html/index.html
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/TEST-*.xml



