version: "2.2"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5460:5432"
    environment:
      POSTGRES_PASSWORD: "gt-i8160"
      POSTGRES_DB: "salon"
    volumes:
      - ./log-directory:/var/lib/postgresql
  beuty-salon:
    build: ../
    restart: always
    ports:
      - "8081:8080"
    environment:
      - DATASOURCE_HOST=db
      - DATASOURCE_PORT=5432
    depends_on:
      - db
